version: '3.8'
services:
  {{ project_name }}_backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8001
    ports:
      - 8001:8001
    volumes:
      - .:/app
    depends_on:
      - db
  {{ project_name }}_pgdb:
    image: postgres:13
    container_name: {{ project_name }}_pgdb
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=userdb
      - POSTGRES_PASSWORD=userpass
    volumes:
      - pgdb_data:/var/lib/postgresql/data
volumes:
    pgdb_data: