version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8001
    ports:
      - 8001:8001
    volumes:
      - .:/app
    depends_on:
      - db
  pgdb:
    image: postgres:13
    container_name: pgdb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdb_data:/var/lib/postgresql/data
volumes:
    pgdb_data: